### ISSUE TITLE
JDBC URL for Cloud Spanner running locally, in docker container

### ISSUE THREAD

**Issue by wise-coders** [googleapis/java-spanner-jdbc#1088]
Is any way to specify a JDBC URL for connecting to a Google Cloud Spanner running locally, as docker container?

**Comment by dsimpson-dcsi** [comment]
I need to test locally with the Google Spanner Emulator, so I set this up in a Docker container. It seems like it would be necessary to be able to connect to a specific IP address (like localhost) and also specify the port# since the port# is configurable in the container configuration.  I am using the Docker image supplied by Google (x86 and ARM64 compatible): docker pull gcr.io/cloud-spanner-emulator/emulator

**Comment by rajatbhatta** [comment]
There are two ways to achieve this:

- Include only the `autoConfigEmulator` connection option in JDBC URL (Connects to http://localhost:9010)
  `cloudspanner:/projects/test-project-123/instances/test-instance-123/databases/test-database-123?autoConfigEmulator=true`
  

- Set specific host/port in JDBC URL in addition to setting `autoConfigEmulator` connection option in JDBC URL:
  `cloudspanner://central-emulator.local:8080/projects/test-project-123/instances/test-instance-123/databases/test-database-123?autoConfigEmulator=true`

**Comment by rajatbhatta** [comment]
Note that the instance and database in the connection string will automatically be created on the emulator if any of them do not yet exist. Any existing instance and/or database will remain untouched.

**Comment by wise-coders** [comment]
Thank you for your help.
