### ISSUE TITLE
Question: recommended usage of spring data for spanner

### ISSUE THREAD

**Issue by Journerist** [googleapis/java-spanner-jdbc#479]
Hi, I want to use spring data in combination with spanner. What is the recommended way of using it?

There is the spring data spanner implementation (https://github.com/spring-cloud/spring-cloud-gcp/tree/main/spring-cloud-gcp-data-spanner) that depends on _google-cloud-spanner_ directly. 

At the same time there is this library for spanner jdbc. There is also _spring-data-jdbc_ that could use this library (java-spanner-jdbc). Also, _liquibase-spanner_ uses _java-spanner-jdbc_. 

I see a risk of using _spring data spanner_ that depends on _google-cloud-spanner_, and liquibase that requires _spanner-jdbc_ that also depends on _google-cloud-spanner_. Using both could end up in same transitive dependency clashes.

What is in a new Java spring boot project the recommended way of having spring data like abstractions and database migrations?

```
a) spring-data-jdbc + java-spanner-jdbc + liquibase-spanner
b) gcp-data-spanner + java-spanner-jdbc + liquibase-spanner (liquibase spanner requires spanner jdbc)

```
I want to use the best support, and long term suggested setup for my services.

Thanks in advance!

**Comment by thiagotnunes** [comment]
@olavloite @elefeint could you help out with this question?

**Comment by elefeint** [comment]
@Journerist For Spring Data JDBC + JDBC driver vs Spring Cloud GCP's Spring Data integration, the answer is straightforward -- it's actually not possible to use Spring Data JDBC directly with the Cloud Spanner driver, since no dialect exists for it. So you should definitely use `spring-cloud-gcp-starter-data-spanner` (this starter module brings in `spring-cloud-gcp-data-spanner` plus the relevant autoconfiguration). Writing a dialect is simple enough, but Spring Cloud GCP's module gives you more functionality that Spring Data JDBC intentionally does not, such as lazy loading of child (interleaved) rows.

To avoid version conflicts, use the [GCP Libraries BOM](https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/The-Google-Cloud-Platform-Libraries-BOM) to manage versions. Spring Cloud GCP modules are not part of the BOM, but they do rely on it, so in most cases using the BOM will get you to an internally consistent set of libraries. It is possible to get into a situation where there is a conflict (such as new BOM and a very old version of Spring Cloud GCP), but this can be resolved by bringing in Spring Cloud GCP that relies on the same major BOM version.

For Liquibase, [this sample](https://github.com/cloudspannerecosystem/liquibase-spanner/tree/master/samples/spanner-liquibase-spring-boot-sample) shows the use of Cloud Spanner's custom Liquibase module with Spring Boot (thanks for the pointer, @olavloite ).

**Comment by Journerist** [comment]
Alright, thanks for clarification !
